version: "3.8"

services:
  nginx:
    container_name : nginx
    build : ./requirements/nginx
    image : nginx
    ports :
      - 443:443
    env_file : .env
    volumes:
      - wordpress:/var/www/html
    networks :
      - inception
    depends_on:
      - wordpress
  
  mariadb:
    container_name : mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file : .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name : wordpress
    build : ./requirements/wordpress
    image: wordpress
    env_file : .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

networks:
  inception:
    name : inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/daniel/data/mariadb
  wordpress:
    name : wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/daniel/data/wordpress
    